/**
 * generated by Xtext 2.24.0
 */
package org.example.workflow.workflowmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.workflow.workflowmodel.TypeReference#getPrimitive <em>Primitive</em>}</li>
 *   <li>{@link org.example.workflow.workflowmodel.TypeReference#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getTypeReference()
 * @model
 * @generated
 */
public interface TypeReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Primitive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive</em>' attribute.
   * @see #setPrimitive(String)
   * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getTypeReference_Primitive()
   * @model
   * @generated
   */
  String getPrimitive();

  /**
   * Sets the value of the '{@link org.example.workflow.workflowmodel.TypeReference#getPrimitive <em>Primitive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primitive</em>' attribute.
   * @see #getPrimitive()
   * @generated
   */
  void setPrimitive(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(EntityType)
   * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getTypeReference_Entity()
   * @model containment="true"
   * @generated
   */
  EntityType getEntity();

  /**
   * Sets the value of the '{@link org.example.workflow.workflowmodel.TypeReference#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(EntityType value);

} // TypeReference
