/*
 * generated by Xtext 2.24.0
 */
package org.example.workflow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WorkflowmodelStandaloneSetup extends WorkflowmodelStandaloneSetupGenerated {

	public static void doSetup() {
		new WorkflowmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
