/**
 * generated by Xtext 2.24.0
 */
package org.example.expression.ide;

import org.example.expression.ide.AbstractExpressionIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ExpressionIdeModule extends AbstractExpressionIdeModule {
}
