/**
 * generated by Xtext 2.24.0
 */
package org.example.expression.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.expression.ExpressionRuntimeModule;
import org.example.expression.ExpressionStandaloneSetup;
import org.example.expression.ide.ExpressionIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ExpressionIdeSetup extends ExpressionStandaloneSetup {
  @Override
  public Injector createInjector() {
    ExpressionRuntimeModule _expressionRuntimeModule = new ExpressionRuntimeModule();
    ExpressionIdeModule _expressionIdeModule = new ExpressionIdeModule();
    return Guice.createInjector(Modules2.mixin(_expressionRuntimeModule, _expressionIdeModule));
  }
}
