/*
 * generated by Xtext 2.24.0
 */
package org.example.expression

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
