/**
 * generated by Xtext 2.24.0
 */
package org.example.expression.expression.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.expression.expression.EvalExpression;
import org.example.expression.expression.ExpressionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Eval Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EvalExpressionImpl extends AbstractElementImpl implements EvalExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvalExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionPackage.Literals.EVAL_EXPRESSION;
  }

} //EvalExpressionImpl
