/**
 * generated by Xtext 2.24.0
 */
package org.example.expression.ui.contentassist;

import com.google.inject.Inject;
import java.util.function.Consumer;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipse.xtext.xbase.lib.Extension;
import org.example.expression.expression.Expression;
import org.example.expression.expression.Variable;
import org.example.expression.ui.contentassist.AbstractExpressionProposalProvider;
import org.example.expression.validation.ExpressionsModelUtil;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ExpressionProposalProvider extends AbstractExpressionProposalProvider {
  @Inject
  @Extension
  private ExpressionsModelUtil _expressionsModelUtil;
  
  @Override
  public void completeAtomic_Variable(final EObject elem, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    if ((elem instanceof Expression)) {
      final Consumer<Variable> _function = (Variable variable) -> {
        String _name = variable.getName();
        String _name_1 = variable.getName();
        String _plus = (_name_1 + " - Variable");
        acceptor.accept(
          this.createCompletionProposal(_name, _plus, null, context));
      };
      this._expressionsModelUtil.variablesDefinedBefore(((Expression)elem)).forEach(_function);
    }
  }
}
