/*
 * generated by Xtext 2.24.0
 */
package org.example.entities.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.entity.ui.internal.EntityActivator;

public class EntitiesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntityActivator.getInstance().getInjector("org.example.entities.Entities");
	}

}
