/**
 * generated by Xtext 2.24.0
 */
package org.example.workflow.workflowmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.workflow.workflowmodel.ConditionElements#getCompareName <em>Compare Name</em>}</li>
 *   <li>{@link org.example.workflow.workflowmodel.ConditionElements#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getConditionElements()
 * @model
 * @generated
 */
public interface ConditionElements extends EObject
{
  /**
   * Returns the value of the '<em><b>Compare Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compare Name</em>' attribute.
   * @see #setCompareName(String)
   * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getConditionElements_CompareName()
   * @model
   * @generated
   */
  String getCompareName();

  /**
   * Sets the value of the '{@link org.example.workflow.workflowmodel.ConditionElements#getCompareName <em>Compare Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compare Name</em>' attribute.
   * @see #getCompareName()
   * @generated
   */
  void setCompareName(String value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getConditionElements_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link org.example.workflow.workflowmodel.ConditionElements#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // ConditionElements
