/**
 * generated by Xtext 2.24.0
 */
package org.example.workflow.workflowmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getDelete()
 * @model
 * @generated
 */
public interface Delete extends Relational
{
} // Delete
