/**
 * generated by Xtext 2.24.0
 */
package org.example.workflow.workflowmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.workflow.workflowmodel.Update#getVariableList <em>Variable List</em>}</li>
 * </ul>
 *
 * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getUpdate()
 * @model
 * @generated
 */
public interface Update extends Relational
{
  /**
   * Returns the value of the '<em><b>Variable List</b></em>' containment reference list.
   * The list contents are of type {@link org.example.workflow.workflowmodel.VariableInit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable List</em>' containment reference list.
   * @see org.example.workflow.workflowmodel.WorkflowmodelPackage#getUpdate_VariableList()
   * @model containment="true"
   * @generated
   */
  EList<VariableInit> getVariableList();

} // Update
