/*
 * generated by Xtext 2.24.0
 */
package org.example.workflow.ide;


/**
 * Use this class to register ide components.
 */
public class WorkflowmodelIdeModule extends AbstractWorkflowmodelIdeModule {
}
