/*
 * generated by Xtext 2.24.0
 */
package org.example.workflow.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class WorkflowmodelEditor extends XbaseEditor {
}
