/*
 * generated by Xtext 2.24.0
 */
package org.example.workflow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WorkflowmodelUiModule extends AbstractWorkflowmodelUiModule {

	public WorkflowmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
