/*
 * generated by Xtext 2.24.0
 */
package org.example.workflow.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.workflow.parser.antlr.internal.InternalWorkflowmodelParser;
import org.example.workflow.services.WorkflowmodelGrammarAccess;

public class WorkflowmodelParser extends AbstractAntlrParser {

	@Inject
	private WorkflowmodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWorkflowmodelParser createParser(XtextTokenStream stream) {
		return new InternalWorkflowmodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ServiceWorkflow";
	}

	public WorkflowmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WorkflowmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
