/**
 * generated by Xtext 2.24.0
 */
package org.example.entities.ui.contentassist;

import org.example.entities.ui.contentassist.AbstractEntitiesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
